"""REST routes for the Insights chat.

GET    /chat/help                          → static, introspected help text
GET    /chat/sessions                      → list all sessions
POST   /chat/sessions                      → create a fresh session, returns id
GET    /chat/sessions/{id}/messages        → full transcript (with charts)
POST   /chat/sessions/{id}/messages        → append a user turn, run AI, persist
                                             and return the assistant turn
DELETE /chat/sessions/{id}                 → delete a session and its messages
"""

from __future__ import annotations

from fastapi import APIRouter, HTTPException

from .. import features
from ..chat import run_chat
from ..help_text import build_help_markdown
from ..models import (
    AppendMessageRequest,
    AppendMessageResponse,
    ChatMessageOut,
    ChatRequest,
    ChatSessionOut,
    ChatTurn,
    WidgetSpec,
)
from ..services import chat_sessions as svc
from ..services.ai.client import AiKeyMissing

router = APIRouter(prefix="/chat", tags=["chat"])


@router.get("/help")
def help_text() -> dict:
    """Static, self-documenting help generated by introspecting the AI's tool
    registries. Adding a tool to ``READ_TOOLS`` / ``WRITE_TOOLS`` automatically
    flows into this response."""
    return {"text": build_help_markdown()}


@router.get("/sessions", response_model=list[ChatSessionOut])
def list_sessions() -> list[ChatSessionOut]:
    return [ChatSessionOut(**s) for s in svc.list_sessions()]


@router.post("/sessions", response_model=ChatSessionOut)
def create_session() -> ChatSessionOut:
    return ChatSessionOut(**svc.create_session())


@router.get("/sessions/{session_id}/messages", response_model=list[ChatMessageOut])
def get_messages(session_id: int) -> list[ChatMessageOut]:
    if svc.get_session(session_id) is None:
        raise HTTPException(status_code=404, detail="session not found")
    return [_message_to_out(m) for m in svc.get_messages(session_id)]


@router.post("/sessions/{session_id}/messages", response_model=AppendMessageResponse)
def append_message(session_id: int, body: AppendMessageRequest) -> AppendMessageResponse:
    if not features.get_flags().get("ai", False):
        raise HTTPException(
            status_code=403,
            detail={"code": "feature_disabled",
                    "message": "AI features are not enabled. Turn them on in Account."},
        )
    if svc.get_session(session_id) is None:
        raise HTTPException(status_code=404, detail="session not found")
    text = (body.text or "").strip()
    if not text:
        raise HTTPException(status_code=400, detail="text is required")

    user_msg = svc.append_message(session_id, "user", text)

    history = svc.get_messages(session_id)
    turns = [ChatTurn(role=m["role"], content=m["text"]) for m in history]
    cost_usd = 0.0
    session_spent_usd = 0.0
    try:
        reply = run_chat(ChatRequest(messages=turns, chat_session_id=session_id))
        assistant_text = reply.text
        widget_payload = reply.widget.model_dump() if reply.widget else None
        cost_usd = reply.cost_usd
        session_spent_usd = reply.session_spent_usd
        errored = False
    except AiKeyMissing as e:
        raise HTTPException(
            status_code=400,
            detail={"code": e.code, "message": str(e)},
        )
    except Exception as e:  # noqa: BLE001
        assistant_text = f"Error: {e}"
        widget_payload = None
        errored = True

    assistant_msg = svc.append_message(
        session_id,
        "assistant",
        assistant_text,
        widget=widget_payload,
        errored=errored,
    )

    return AppendMessageResponse(
        user_message=_message_to_out(user_msg),
        assistant_message=_message_to_out(assistant_msg),
        cost_usd=cost_usd,
        session_spent_usd=session_spent_usd,
    )


@router.delete("/sessions/{session_id}")
def delete_session(session_id: int) -> dict:
    ok = svc.delete_session(session_id)
    if not ok:
        raise HTTPException(status_code=404, detail="session not found")
    return {"ok": True}


def _message_to_out(m: dict) -> ChatMessageOut:
    widget = WidgetSpec(**m["widget"]) if m.get("widget") else None
    return ChatMessageOut(
        id=m["id"],
        sequence=m["sequence"],
        role=m["role"],
        text=m["text"],
        widget=widget,
        errored=bool(m.get("errored", False)),
        created_at=m["created_at"],
    )
