"""REST routes for the Insights chat.

GET    /chat/help                          → static, introspected help text
GET    /chat/sessions                      → list all sessions
POST   /chat/sessions                      → create a fresh session, returns id
GET    /chat/sessions/{id}/messages        → full transcript (with charts)
POST   /chat/sessions/{id}/messages        → append a user turn, run AI, persist
                                             and return the assistant turn
DELETE /chat/sessions/{id}                 → delete a session and its messages
"""

from __future__ import annotations

from fastapi import APIRouter, HTTPException

from .. import features
from ..chat import run_chat
from ..help_text import build_help_markdown
from ..models import (
    AppendMessageRequest,
    AppendMessageResponse,
    ChartSpec,
    ChatMessageOut,
    ChatRequest,
    ChatSessionOut,
    ChatTurn,
)
from ..services import chat_sessions as svc

router = APIRouter(prefix="/chat", tags=["chat"])


@router.get("/help")
def help_text() -> dict:
    """Static, self-documenting help generated by introspecting the AI's tool
    registries. Adding a tool to ``READ_TOOLS`` / ``WRITE_TOOLS`` automatically
    flows into this response."""
    flags = features.get_flags()
    text = build_help_markdown(with_writes=bool(flags.get("ai_mutations", False)))
    return {"text": text}


@router.get("/sessions", response_model=list[ChatSessionOut])
def list_sessions() -> list[ChatSessionOut]:
    return [ChatSessionOut(**s) for s in svc.list_sessions()]


@router.post("/sessions", response_model=ChatSessionOut)
def create_session() -> ChatSessionOut:
    return ChatSessionOut(**svc.create_session())


@router.get("/sessions/{session_id}/messages", response_model=list[ChatMessageOut])
def get_messages(session_id: int) -> list[ChatMessageOut]:
    if svc.get_session(session_id) is None:
        raise HTTPException(status_code=404, detail="session not found")
    return [_message_to_out(m) for m in svc.get_messages(session_id)]


@router.post("/sessions/{session_id}/messages", response_model=AppendMessageResponse)
def append_message(session_id: int, body: AppendMessageRequest) -> AppendMessageResponse:
    if svc.get_session(session_id) is None:
        raise HTTPException(status_code=404, detail="session not found")
    text = (body.text or "").strip()
    if not text:
        raise HTTPException(status_code=400, detail="text is required")

    user_msg = svc.append_message(session_id, "user", text)

    history = svc.get_messages(session_id)
    turns = [ChatTurn(role=m["role"], content=m["text"]) for m in history]
    try:
        reply = run_chat(ChatRequest(messages=turns))
        assistant_text = reply.text
        chart_payload = reply.chart.model_dump() if reply.chart else None
        errored = False
    except Exception as e:  # noqa: BLE001
        assistant_text = f"Error: {e}"
        chart_payload = None
        errored = True

    assistant_msg = svc.append_message(
        session_id,
        "assistant",
        assistant_text,
        chart=chart_payload,
        errored=errored,
    )

    return AppendMessageResponse(
        user_message=_message_to_out(user_msg),
        assistant_message=_message_to_out(assistant_msg),
    )


@router.delete("/sessions/{session_id}")
def delete_session(session_id: int) -> dict:
    ok = svc.delete_session(session_id)
    if not ok:
        raise HTTPException(status_code=404, detail="session not found")
    return {"ok": True}


def _message_to_out(m: dict) -> ChatMessageOut:
    chart = ChartSpec(**m["chart"]) if m.get("chart") else None
    return ChatMessageOut(
        id=m["id"],
        sequence=m["sequence"],
        role=m["role"],
        text=m["text"],
        chart=chart,
        errored=bool(m.get("errored", False)),
        created_at=m["created_at"],
    )
